### ISSUE TITLE
Manual installation process

### ISSUE THREAD

**Issue by rareslupascu** [streem/react-native-select-contact#2]
Hi

was thinking to use ur package but i would need the manual installation steps ... is it possible?

thanks

**Comment by seanadkinson** [comment]
Hi there.  The manual instructions are the same for any react-native package.  Just involves making the code available to native IOS and Android.  This is all `react-native link` does though, so I'm curious why you wouldn't use it.  If you have non-standard installation that `link` doesn't work for, then the manual instructions wouldn't work anyway.

Follow instructions for any react-native manual link package to link this one, if you like.  And if there was anything worth documenting, would love to accept a PR for the README.

Thank you!
