### ISSUE TITLE
Version 1.3.1 iOS build failed

### ISSUE THREAD

**Issue by HieuDevX** [streem/react-native-select-contact#24]
I install version 1.3.1 but when I build on XCode, it failed, it just works on android.
It works when I install version 1.3.0 on both android and ios.

This is screen shot link XCode build error: 
https://drive.google.com/open?id=17Sc-shNodRmdcywdXpFESQ7Zb-gjxDzW

"react-native": "0.61.5",
"@react-navigation/native": "^5.0.0",
XCode 11.3.1 (11C504)

**Comment by seanadkinson** [comment]
Reverted the commit, and published `v.1.3.2`
