### ISSUE TITLE
i have error like this with react-native-select-contact 

### ISSUE THREAD

**Issue by prakashsaran** [streem/react-native-select-contact#29]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-select-contact.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-select-contact:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at makeError (/Users/apple/Desktop/workspace/react_native/EzyRent/node_modules/execa/index.js:174:9)
    at /Users/apple/Desktop/workspace/react_native/EzyRent/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (/Users/apple/Desktop/workspace/react_native/EzyRent/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/apple/Desktop/workspace/react_native/EzyRent/node_modules/@react-native-community/cli/build/index.js:186:9)

**Comment by yusufozcan** [comment]
Same for me

**Comment by anwartan** [comment]
i get same error

**Comment by lgenzelis** [comment]
The error is related to auto-linking. I found [this fork](https://github.com/hazesoftco/react-native-select-contact) which solves the issue.

**Comment by seanadkinson** [comment]
@prakashsaran or @lgenzelis , does PR #27 fix this issue for you?  We don't use this module in-house anymore, so if you can help us determine the fix, I'm happy to merge and publish.  Thanks!

**Comment by DriesVS** [comment]
PR works, just as originally commented on PR. We're already using it in production.

@seanadkinson you guys are nog longer using/actively maintaining this library. How do we move forward from here? There are several PR's open that fix major bugs. I'm willing to help review future PR's and release new versions.

**Comment by seanadkinson** [comment]
Yes, if you can help review and verify fixes, I can merge and publish.  Happy to look into making you a maintainer as well, if interested.

**Comment by DriesVS** [comment]
@seanadkinson sounds good! For now, I'd really love to see #27 get merged.

**Comment by seanadkinson** [comment]
Published `v1.5.0` after merging that PR.  Thanks!

**Comment by DriesVS** [comment]
@seanadkinson 🎉 works

**Comment by sujatha2016** [comment]
am still getting this issue... with version 1.5.0
