### ISSUE TITLE
Cannot read property 'openContactSelection' of undefined

### ISSUE THREAD

**Issue by GitHubGreg** [streem/react-native-select-contact#4]
I have been unable to get this working, even using your exact example code. I get the error:

Cannot read property 'openContactSelection' of undefined

**Comment by seanadkinson** [comment]
Probably just an import configuration issue.  Here is how we are exporting: https://github.com/streem/react-native-select-contact/blob/master/index.js#L106

You might try importing differently:

    import SelectContact from 'react-native-select-contact'
    ...
    SelectContact.openContactSelection()

We use typescript, and it works as expected.  Please report back here if it works for you.  Thanks!

**Comment by GitHubGreg** [comment]
Thanks. I ended up using something else, but thanks for the reply nonetheless.

**Comment by ashishKv** [comment]
I am getting same error 'openContactSelection' is undefined and I am not able to access this function from any method.

**Comment by bhagwandas** [comment]
You may get this error if you forget to link

**Comment by moxspoy** [comment]
@bhagwandas answer works for me, thank you
