### ISSUE TITLE
Issue in Android 11, Contact picker not open

### ISSUE THREAD

**Issue by SomnathKadam** [streem/react-native-select-contact#42]
Hi Team,

facing issue in Android 11 Contact picker not open, with below code 

`import { selectContactPhone } from 'react-native-select-contact';`

```

const requestContactPermission = async () => {
        try {
            const granted = await PermissionsAndroid.request(
                PermissionsAndroid.PERMISSIONS.READ_CONTACTS,
                {
                    title: 'Allow Access Contact?',
                    message: 'allow this app to read contact information',
                    buttonNegative: 'Cancel',
                    buttonPositive: 'OK'
                }
            );
            if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                getPhoneNumber();
            }
        } catch (err) {
            console.warn(err);
        }
    };



const getPhoneNumber = async () => {
        selectContactPhone()
            .then((selection) => {
                if (!selection) {
                    return null;
                }
                let { contact, selectedPhone } = selection;
                console.log(
                    `Selected ${selectedPhone.type} phone number ${selectedPhone.number} from ${contact.name}`
                );

                
            })
            .catch((err) => {
                console.log(err);
            });
    };
```

solution : Need to add below lines in AndroidManifest

```
......
</application>
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <data android:mimeType="vnd.android.cursor.dir/contact" />
        </intent>
    </queries>
</manifest>
```

**Comment by SomnathKadam** [comment]
solution : Need to add below lines in AndroidManifest

```
......
</application>
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <data android:mimeType="vnd.android.cursor.dir/contact" />
        </intent>
    </queries>
</manifest>
```

**Comment by aruhn1** [comment]
For any future visitors to this issue - 
The underlying reference is this - 

https://developer.android.com/training/package-visibility

**Comment by thanhluantl2304** [comment]
this should be added to Documentation

**Comment by bijaykanshinew** [comment]
i added this line

> <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <data android:mimeType="vnd.android.cursor.dir/contact" />
        </intent>
    </queries>

but it's still not working. it's closing the app without any error

**Comment by imamrobani** [comment]
> <action android:name="android.intent.action.VIEW" />
>             <category android:name="android.intent.category.DEFAULT" />
>             <data android:mimeType="vnd.android.cursor.dir/contact" />

yes, I still facing this issue on android 11, anyone can help?

**Comment by imamrobani** [comment]
> i added this line
> 
> ```
> <queries>
>     <intent>
>         <action android:name="android.intent.action.VIEW" />
>         <category android:name="android.intent.category.DEFAULT" />
>         <data android:mimeType="vnd.android.cursor.dir/contact" />
>     </intent>
> </queries>
> ```
> 
> but it's still not working. it's closing the app without any error

yes, I still facing this issue on android 11, anyone can help?

**Comment by flyjeray** [comment]
Late answer but I've encountered the same problem:

If you don't really know, how AndroidManifest works (as example, I don't), make sure that you don't mix intent blocks

```
<intent>
      <action android:name="android.intent.action.VIEW" />
      <category android:name="android.intent.category.DEFAULT" />
      <data android:mimeType="vnd.android.cursor.dir/contact" />
      <category android:name="android.intent.category.BROWSABLE"/>
      <data android:scheme="https"/>
</intent>
```

**^ This will NOT work ^**

```
<intent>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data android:scheme="https"/>
</intent>
<intent>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <data android:mimeType="vnd.android.cursor.dir/contact" />
</intent>
```

**^ This is correct ^**

A bit dumb situation, but it's better to save other beginners from spending hours on this :)
