### ISSUE TITLE
mContactsPromise.reject ERROR

### ISSUE THREAD

**Issue by lejiangkai** [streem/react-native-select-contact#7]
private void launchPicker(Promise contactsPromise, int requestCode) {
        Cursor cursor = this.contentResolver.query(Contacts.CONTENT_URI, null, null, null, null);
        mContactsPromise = contactsPromise;
        if (cursor != null) {
//            mContactsPromise = contactsPromise;
            Intent intent = new Intent(Intent.ACTION_PICK);
            intent.setType(Contacts.CONTENT_TYPE);
            Activity activity = getCurrentActivity();
            if (intent.resolveActivity(activity.getPackageManager()) != null) {
                activity.startActivityForResult(intent, requestCode);
            }
            cursor.close();
        } else {
            mContactsPromise.reject(E_CONTACT_PERMISSION, "no permission");
        }

**Comment by seanadkinson** [comment]
Looks like it will reject if the app doesn't have access to contacts.  Please re-open if there is more information, or specific questions.  Thanks!
