### ISSUE TITLE
react-native =>0.60.0 requires a podspec file

### ISSUE THREAD

**Issue by kirkryan** [streem/react-native-select-contact#8]
Hi, 

I have got this working by running react-native link react-native-select-contact then having to manually import and reference React itself within my project, but with RN 0.60.0+ there is no longer a requirement to link libraries, such as this one.

Installation would be easier if there was a pod file for installation, do you have on (it's now the defacto standard for all current react-native libraries?).

If not happy to help when I get a chance.

**Comment by kirkryan** [comment]
I have now created the podspec file and raised the PR: https://github.com/streem/react-native-select-contact/pull/9
@seanadkinson - can you review and merge?

Also the installation instructions need updating. react-native link react-native-select-contact is no longer required in >=RN 0.60.0.

iOS users must simply `yarn add react-native-select-contact` then `cd ios & pod install`

**Comment by seanadkinson** [comment]
@kirkryan Very cool, thank you for the PR!  We haven't looked closely at RN 0.60+, but the changes look safe to merge, so will get that released.
